### PR TITLE
7 as a user i need a registration page so that i can register

### LINKED ISSUE #7: As a user, I need a registration page so that I can register

### PR DESCRIPTION
**Pull request by napu002**
Registration page changes
Submits the new user details in Vercel URL

### CODE REVIEW

**Review by sagarnepali378 — CHANGES_REQUESTED** [review]
After the code review, i found the layout of form is not appropriate. we can align the form in justifiable manner.
I suggest to align the labels and input fields in the same columns.

**Review by SeasonGit10 — CHANGES_REQUESTED** [review]
After the code review, i found the naming identifier for "**password2**" might not be suitable for the user, instead we can use "**password_confirm**" .
I suggest to use "**register_status**" inplace of "RegStatus"

**Review by napu002 — COMMENTED** [review]
I have worked on the changes mentioned in your review.

**Review by sagarnepali378 — APPROVED** [review]
Now i have seen the changes and looks appropriate.

**Review by SeasonGit10 — APPROVED** [review]
I found  the changes made in the code while reviewing the code. 
Thank you!!

**Pull request merged**
