### PR TITLE
added product page

### LINKED ISSUE #14: As a user, I want a new product page so that I can calculate product of two numbers

### PR DESCRIPTION
**Pull request by sagarnepali378**
this page includes a form to calculate product of two entered numbers

### CODE REVIEW

**Review by napu002 — CHANGES_REQUESTED** [review]
After testing, I found that the operator for the product is incorrect. Please change the operator from '/' to '*' for product in calc() function.

**Review by SeasonGit10 — CHANGES_REQUESTED** [review]
As a reviewer, I thinks its better to change the "num1" and "num2" variable as  *"FirstNumber"* and *SecondNumber"* for the proper naming convention!!

**Review by napu002 — APPROVED** [review]
Product is now correct. Thank you.

**Review by SeasonGit10 — APPROVED** [review]
Approved!! Thanks

**Pull request merged**
