### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by SeasonGit10**

### CODE REVIEW

**Review by napu002 — CHANGES_REQUESTED** [review]
It's better if you change "pswd" to "password" for better naming convention.

For error message, change the login status text to "Sorry! Username/Password incorrect. Please try again."

**Review by sagarnepali378 — COMMENTED** [review]
Its better to align the login form in proper manner for visualization. can you please make it?

**Review by napu002 — APPROVED** [review]
All the requested changes have been confirmed. It's fine now. Thank you.

**Review by sagarnepali378 — APPROVED** [review]
Thank you for changing all the request.

**Pull request merged**
